Use GitHub action
TeamMomentum/bs-url-normalizer pull request #100
Opened 2023-03-30 03:32 UTC by dictav

2023-03-31 06:38 UTC, t4110 requested changes
1箇所だけコメントしました
他はLGTMです :ok_man:

2023-03-31 06:38 UTC, t4110 commented on .github/workflows/go.yaml
> +          version: latest
jsやresources内のファイルのみ更新したときなどにもテストが失敗するようになると煩わしいので、golangci-lint のバージョンは固定したいです

2023-03-31 06:44 UTC, dictav commented on .github/workflows/go.yaml
> +          version: latest
JSのコード修正時は動かないようにしてます。
他にも README や .github なども追加しましょうか？
https://github.com/TeamMomentum/bs-url-normalizer/pull/100/files#diff-59b0366afbddbafb181605e979731c2c5b7e104711ff2158c2dff2198cc6b882R4-R5

2023-03-31 06:48 UTC, t4110 commented on .github/workflows/go.yaml
> +          version: latest
それよりも、勝手に壊れる前提のCIを作りたくないですね
golangci-lintのバージョンアップは常に意図的に行われるべきだと思っています

2023-04-03 08:57 UTC, dictav commented on .github/workflows/go.yaml
> +          version: latest
なるほど。基本実行されるのは修正時のみなので `latest` の方が忘れなくて良いかなと思ったんですが。
編集時は忘れないように気をつけます。

2023-04-03 09:49 UTC, dictav commented on .github/workflows/go.yaml
> +          version: latest
ad07551

2023-04-03 09:51 UTC, t4110 approved these changes
LGTM :ok_hand: 

ご対応ありがとうございます!

2023-04-03 09:52 UTC, merged